inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  
Layout/LineLength:
  Exclude:
    - "spec/system/bitklavier_form_submission_spec.rb"
    - "spec/system/sowingseeds_spec.rb"
    - "spec/system/attention_form_submission_spec.rb"
    - "spec/system/cytoskeletal_form_submissiion_spec.rb"
    - "spec/system/femtosecond_form_submission_spec.rb"
    - "spec/system/cytoskeletal_form_submission_spec.rb"
    
Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
    - "app/models/work.rb"

Metrics/ClassLength:
  Exclude:
    - "app/services/s3_query_service.rb"

Metrics/MethodLength:
  Exclude:
    - "app/models/work.rb"
    - "spec/support/work_s3_requests_specs.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - "app/controllers/works_controller.rb"

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
