inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  
Layout/LineLength:
  Exclude:
    - "spec/system/data_migration/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
    - "config/routes.rb"
  Max: 40 # default: 25

Metrics/ClassLength:
  Exclude: []
  Max: 150 # default: 100

Metrics/MethodLength:
  Exclude:
    - "app/models/s3_file.rb"
  Max: 15 # default: 10

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude: []

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
