inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.1
  DisabledByDefault: true
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  
Layout/LineLength:
  Exclude:
    - "spec/system/data_migration/*"

Metrics/AbcSize:
  Exclude:
    - app/models/work_activity.rb

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
    - "config/routes.rb"
  Max: 40 # default: 25

Metrics/ClassLength:
  Exclude: []
  Max: 150 # default: 100

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/work_activity.rb

Metrics/MethodLength:
  Exclude:
    - app/models/s3_file.rb
    - app/models/work_activity.rb
    - app/jobs/approved_file_move_job.rb
    - app/services/s3_query_service.rb
  Max: 15 # default: 10

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - app/models/work_activity.rb

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - app/models/ark.rb
    - app/services/work_update_metadata_service.rb

Rails/UnknownEnv:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
