---
shared:
  pppl:
    admin:
      - tbd-001
    submit:
      - tbd-002
      - tbd-003
      - hc8719
  rd:
    admin:
      - tbd-004
    submit:
      - tbd-005
      - tbd-006
  etd:
    admin:
      - tbd-007
  lib:
    submit:
      - tbd-008
    admin:
      - hc8719


