---
shared:
  rd:
    admin:
      - tbd-004
    submit:
      - tbd-005
      - tbd-006
  pppl:
    admin:
      - tbd-001
    submit:
      - tbd-002
      - tbd-003
test:
  rd:
    admin:
      - user1
    submit:
      - user2
  pppl:
    admin:
    submit:
      - user3
