---
# Some objects have data so large the files cannot be automatically fetched
# from DataSpace and they must be moved manually. To indicate that the system should
# not attempt to manually migrate these data files, enter the ARK here.
default: &default
  arks:
    - ark:/88435/dsp01h415pd457 # Distinct cytoskeletal proteins define zones of enhanced cell wall synthesis in Helicobacter pylori
production:
  <<: *default
staging:
  <<: *default
development:
  <<: *default
test:
  <<: *default

