# These users are given a form below the change log that lets them add back-dated free-text messages.
development:
  - bs3097
  - cac9
  - cl7359
  - fn8243
  - hc8719
  - hh4079
  - jrg5
  - kl37

staging:
  - bs3097
  - cac9
  - cl7359
  - fn8243
  - hb0344
  - hc8719
  - hh4079
  - jrg5
  - kl37
  - meghant
  - mjc12
  - neggink
  - sr7276

test:
  - bs3097
  - cac9
  - cl7359
  - fn8243
  - hc8719
  - hh4079
  - jrg5
  - kl37

production:
  - bs3097
  - cac9
  - cl7359
  - fn8243
  - hb0344
  - hc8719
  - hh4079
  - jrg5
  - kl37
  - meghant
  - mjc12
  - neggink
  - sr7276
