# These users are given a form below the change log that lets them add back-dated free-text messages.
development:
  - bs3097
  - cac9
  - hh4079
  - jh6441
  - jrg5
  - kl37
  - pp9425
  - rl3667

staging:
  - bs3097
  - cac9
  - hh4079
  - jh6441
  - jrg5
  - kl37
  - meghant
  - mjc12
  - neggink
  - pp9425
  - rl3667
  - sr7276

test:
  - bs3097
  - cac9
  - hh4079
  - jh6441
  - jrg5
  - kl37
  - pp9425
  - rl3667

production:
  - bs3097
  - cac9
  - hh4079
  - jh6441
  - jrg5
  - kl37
  - meghant
  - mjc12
  - neggink
  - pp9425
  - rl3667
  - sr7276
